PREFIX p510: <http://www.lotar.org/schemas/mbse/p510#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?req ?id ?state
WHERE {
  ?req rdf:type p510:Requirement ;
       p510:Id ?id .
  OPTIONAL { ?req p510:Approval_State ?state }
  FILTER NOT EXISTS { ?req p510:Approver ?a }
}
ORDER BY ?id
