PREFIX p510: <http://www.lotar.org/schemas/mbse/p510#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?org (COUNT(DISTINCT ?req) AS ?numRequisitos)
WHERE {
  ?req rdf:type p510:Requirement .
  OPTIONAL { ?req p510:Author_Organization ?org }
}
GROUP BY ?org
ORDER BY DESC(?numRequisitos)
