PREFIX p510: <http://www.lotar.org/schemas/mbse/p510#>

# Duplicate trace: same source + predicate + target in more than one link-node
SELECT ?src ?pred ?target (COUNT(DISTINCT ?link) AS ?numLinks)
WHERE {
  VALUES ?pred { p510:Satisfied_by p510:Verified_by p510:Validated_by p510:uses }
  ?src ?pred ?link .
  ?link p510:Link ?target .
}
GROUP BY ?src ?pred ?target
HAVING(COUNT(DISTINCT ?link) > 1)
ORDER BY DESC(?numLinks)
