PREFIX p510:   <http://www.lotar.org/schemas/mbse/p510#>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex:     <http://example.org/tfg/mbse#>
PREFIX dcterms:<http://purl.org/dc/terms/>

SELECT ?projectCode ?product ?baselineName ?baselineId ?baselineCreated
WHERE {
  ?manifest rdf:type p510:P510_ManifestType ;
            p510:has_GeneralPLMInfo ?info .

  OPTIONAL { ?info ex:project_code ?projectCode }
  OPTIONAL { ?info ex:product ?product }
  OPTIONAL {
    ?info ex:hasBaseline ?bl .
    OPTIONAL { ?bl ex:baseline_name ?baselineName }
    OPTIONAL { ?bl ex:baseline_id ?baselineId }
    OPTIONAL { ?bl dcterms:created ?baselineCreated }
  }
}
