PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX p510: <http://www.lotar.org/schemas/mbse/p510#>

SELECT (100.0 * COUNT(DISTINCT ?reqConModelo) / COUNT(DISTINCT ?req) AS ?porcentaje)
WHERE {
  ?req rdf:type p510:Requirement .
  OPTIONAL {
    ?req p510:Satisfied_by ?link .
    ?link p510:ContentType "Physical Model" ;
          p510:Link ?modelo .
    BIND(?req AS ?reqConModelo)
  }
}
