PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX p510: <http://www.lotar.org/schemas/mbse/p510#>

SELECT ?elemento
WHERE {
  ?elemento rdf:type ?tipo .
  FILTER NOT EXISTS { ?elemento p510:Satisfied_by ?o }
  FILTER NOT EXISTS { ?s p510:Satisfied_by ?elemento }
  FILTER NOT EXISTS { ?elemento p510:Verified_by ?o2 }
  FILTER NOT EXISTS { ?s2 p510:Verified_by ?elemento }
}