PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX p510: <http://www.lotar.org/schemas/mbse/p510#>

SELECT ?req ?id ?desc
WHERE {
    # 1. Buscamos cosas que sean Requisitos
    ?req rdf:type p510:Requirement .
    ?req p510:id ?id .
    OPTIONAL { ?req p510:description ?desc }

    # 2. FILTRO CLAVE: Que NO exista una relación 'Satisfied_by'
    FILTER NOT EXISTS {
        ?req p510:Satisfied_by ?modelo .
    }
}