PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX p510: <http://www.lotar.org/schemas/mbse/p510#>

SELECT ?tipo (COUNT(?x) AS ?total)
WHERE {
  { ?x rdf:type p510:Requirement . BIND("Requisitos" AS ?tipo) }
  UNION
  { ?x rdf:type p510:DesignModel . BIND("Modelos" AS ?tipo) }
  UNION
  { ?x rdf:type p510:VerificationTest . BIND("Tests" AS ?tipo) }
}
GROUP BY ?tipo